# Generated by Django 4.2.4 on 2023-08-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0002_bill_status_billitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
