# Generated by Django 4.2.4 on 2023-08-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientuser_labuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labuser',
            old_name='contry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='patientuser',
            old_name='contry',
            new_name='country',
        ),
    ]
